// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderTracker.Data;

#nullable disable

namespace OrderTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("OrderTracker.Models.Order", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTime?>("EstimatedDelivery").HasColumnType("TEXT");
                b.Property<DateTime?>("ReceivedDate").HasColumnType("TEXT");
                b.Property<bool>("IsDeleted").HasColumnType("INTEGER");
                b.Property<string>("Notes").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<DateTime>("PurchaseDate").HasColumnType("TEXT");
                b.Property<int>("ShippingCompany").HasColumnType("INTEGER");
                b.Property<int>("Status").HasColumnType("INTEGER");
                b.Property<string>("Store").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("TrackingCode").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("TrackingUrl").HasColumnType("TEXT");
                b.Property<decimal>("TotalPrice").HasColumnType("decimal(18,2)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Orders");
            });

            modelBuilder.Entity("OrderTracker.Models.OrderItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("OrderId").HasColumnType("INTEGER");
                b.Property<string>("ProductName").IsRequired().HasMaxLength(300).HasColumnType("TEXT");
                b.Property<int>("Quantity").HasColumnType("INTEGER");
                b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.ToTable("OrderItems");
            });

            modelBuilder.Entity("OrderTracker.Models.OrderItem", b =>
            {
                b.HasOne("OrderTracker.Models.Order", "Order")
                    .WithMany("Items")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Order");
            });

            modelBuilder.Entity("OrderTracker.Models.Order", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}
